### ISSUE TITLE
Avoid URL being changed

### ISSUE THREAD

**Issue by yfdyh000** [scorzy/IdleAnt#15]
Like `https://scorzy.github.io/IdleAnt/main/unit/unit/G1`, this leads the users to a non-existent page in the future. How to avoid it being changed (e.g. a `iframe`?), or keep it (e.g. [History API](https://developer.mozilla.org/en-US/docs/Web/API/History)?).

**Comment by scorzy** [comment]
fixed with # url, now url are like https://scorzy.github.io/IdleAnt/#/main/unit/unit/G1 and works
