### ISSUE TITLE
units consume 5% less resources. Max -50%

### ISSUE THREAD

**Issue by gloony** [scorzy/IdleAnt#17]
Hi,

I found a error on Experience Tab.
For all Bonus with label "units consume 5% less resources. Max -50%", is impossible to level it to level 10 if we level it one by one. It block to 9.
If we level 10 level in one click, it work fine.

By the way, I love your game :), it a great past time activity ^^

Regards,
gloony

**Comment by scorzy** [comment]
Thanks for reporting,
now should be fixed (v. 0.2.3)
