### ISSUE TITLE
Breaking gameplay with a mega boost of experience

### ISSUE THREAD

**Issue by gloony** [scorzy/IdleAnt#19]
I found a way to break the gameplay of the game.
When you unlock the **_World Generator_**, you can make a stage to level 10000.
Even if you don't go to the Travel requirement, the labotory  give you a lot of experience (when you unlock the x3 bonus [_**Evolution**_], and 50% of experience now [_**Here and Now 2**_]).

You can repeat that by skiping actual world and earn Billion of experience at a low level.

I think the best will be to limit the max world you can generate by the max level you had already reach by standard world.
A second idea is to change the **_Here and Now 2_** Bonus, with a simple boost of experience earn by Traval to a new world.

I don't know if you want to me to hide this message, by editing it, for avoid using it by another person ?

**Comment by scorzy** [comment]
A second idea is to change the Here and Now 2 Bonus, with a simple boost of experience earn by Traval to a new world.
I did this, now it give +50% whe travel.

**Comment by gloony** [comment]
For my own propose I rename the "Here and Now 2" to "Over and Beyond", cause is no instant anymore.

And I make a little change to "Here and Now" being more attractive, I see you are on the way to make the IdleAnt2, but I still play to this one because I love it :)
```
if(e.game.world.level>100) var ne = e.game.world.level / 10;
else var ne = 10;
if(e.game.prestige.experience.quantity>ne) ne = e.game.prestige.experience.quantity / 10;
if(ne>e.game.world.level) ne = e.game.world.level ;
e.game.prestige.experience.quantity = e.game.prestige.experience.quantity.plus(ne), e.game.maxLevel = e.game.maxLevel.plus(10), e.game.expTabAv = !0
```

**Comment by scorzy** [comment]
changed with last commit
