### ISSUE TITLE
Save/Restore Issue: Mole

### ISSUE THREAD

**Issue by Mythran101** [scorzy/IdleAnt#22]
When you research Mole, save the game, close the game, and then resume the game at a later time, it seems the Mole research is available to click on again from the research page.  Same thing happens for another research issue, IIRC, but I don't remember at this point.  If I see another, I'll create another issue.

**Comment by Mythran101** [comment]
It's Mole and Mole Nest that appear.  Found another set of issues with mole's n their associated nest too, but I'll post another issue for that.

**Comment by scorzy** [comment]
Fixed. The other research probably was "Scientist Mole". The problem researches with the same game id (the string i use for identity stuff when saving/loading).
