### ISSUE TITLE
Another Save/Restore Issue with Mole/Mole Nests

### ISSUE THREAD

**Issue by Mythran101** [scorzy/IdleAnt#25]
The following affects both mole's and mole nests (not just moles).

Moles and Mole Nests dissappear, even though they were researched and unlocked prior to saving and restoring the game (either through saving and then coming back to the game or through import/export methods afaik) so long as the mole or mole nests was researched AND no mole's or mole nests were actually bought before saving/restoring.

To reproduce, perform the research to unlock the mole (or mole nest if mole is unlocked already).  Do not purchase any moles (or mole nests).  Save the game.  Close the game.  Launch the game (in browser or the mobile app).  Moles and Mole Nests are not available to buy.

**Comment by scorzy** [comment]
Ok i get, i will try to fix it

**Comment by scorzy** [comment]
The last update may have fixed it. I will check in the next days.
