### ISSUE TITLE
No scroll bar on left sidebar

### ISSUE THREAD

**Issue by yfdyh000** [scorzy/IdleAnt#8]
Looks the "0.0.10 - 31-10-2017" removes the scroll bar.

I think this reduces the availability / readability of the left sidebar for small screen.
If this has to be removed, I suggest add automatically expand selected section, allowing pin sections, and other sections to be folded automatically.

**Comment by scorzy** [comment]
Fixed on firefox, i ma add an option to auto fold other section

**Comment by yfdyh000** [comment]
Looks good now. autofold or pin sections may be unnecessary now.
